### PR TITLE
Update tunnel ssh

### PR DESCRIPTION
**Pull request by evoactivity**
Continues #10

- add prettier
- add ability to pass private key contents as well as file path
- add password as an option
- add passphrase as an option for protected private keys

### CODE REVIEW

**Comment by evoactivity** [comment]
@lukemelia Any chance of a review/merge?

**Comment by lukemelia** [comment]
Hi @evoactivity, it looks like the configuration option to provide your own tunnelClient has been removed. What is the migration path for people who were using this option?

**Comment by evoactivity** [comment]
Ahh, that was an oversight. I'll add it back in 👍

**Comment by evoactivity** [comment]
Added that back in.

**Comment by lukemelia** [comment]
Thanks @evoactivity and @jdaviderb!

**Comment by lukemelia** [comment]
Released as [v2.0.0](https://github.com/ember-cli-deploy/ember-cli-deploy-ssh-tunnel/releases/tag/v2.0.0)

**Pull request merged**
