### PR TITLE
Add more detail in the quickstart guide for setup with ember-cli-deploy-redis

### PR DESCRIPTION
**Pull request by g-cassie**
Please feel free to edit.  This took me a little a bit of poking around the ember-cli-deploy docs and examples to figure out for myself so I think it could save some time for the next person.

### CODE REVIEW

**Comment by ghedamat** [comment]
thanks for this @g-cassie 
This has very good timing with https://github.com/ember-cli-deploy/ember-cli-deploy-redis/pull/38

It would be great if you could rework this PR a bit to better explain how ssh-tunnel can now work with the redis plugin

**Comment by ghedamat** [comment]
also mind prefixing your commit with `[DOC]` 

thanks!

**Comment by g-cassie** [comment]
Ok, looks like those changes should make the config work out of the box.  Once a release is cut with ember-cli-deploy/ember-cli-deploy-redis#38 I will revise my comments and add a reference to the minimum version number for ember-cli-redis that is needed for the auto config to work.

**Comment by ghedamat** [comment]
@g-cassie perfect, I'll ping you when we release the other plugin, just waiting to merge a couple of PRs

**Comment by ghedamat** [comment]
@g-cassie ok, just released 0.1.1 of ember-cli-deploy-redis

**Comment by ghedamat** [comment]
@g-cassie ping in case you have a sec to finish this

**Comment by g-cassie** [comment]
@ghedamat Thanks - I just pushed a rebased commit.  It seems that this basically works right out of the box now so I basically am just providing some background on how it works.  Let me know if you want me to make any changes.

 Sorry for the delay!

**Comment by ghedamat** [comment]
Thank you!

**Pull request merged**
